bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0
users:
- name: root
  password: $2y$10$8GfLmnbQpS883RMTpGN66.TbyavsPmElcy2aR6vec7xL0YOG.gx52
http_proxy: ""
language: ""
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_host: 127.0.0.1
  port: 5333
  statistics_interval: 7
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 7
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 60
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - 114.114.114.114
  - 101.226.4.6
  - 2400:3200::1
  - '[/majork.win/]114.114.114.114'
  - '[/c3s3.jamjams.net/]114.114.114.114'
  - '[/c3s4.jamjams.net/]114.114.114.114'
  - '[/c3s5.jamjams.net/]114.114.114.114'
  upstream_dns_file: ""
  bootstrap_dns:
  - 218.2.2.2
  - 240e:5a::6666
  all_servers: true
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  cache_size: 4194304
  cache_ttl_min: 3600
  cache_ttl_max: 36000
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: false
  max_goroutines: 0
  ipset: []
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: true
  safebrowsing_enabled: true
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites:
  - domain: wifi.weixin.qq.com
    answer: 127.0.0.1
  - domain: clock.redhat.com
    answer: cn.ntp.org.cn
  - domain: clock.cuhk.edu.hk
    answer: cn.ntp.org.cn
  - domain: https://www.meituan.com
    answer: www.meituan.com
  - domain: image.tmdb.org
    answer: 104.16.61.155
  - domain: api.themoviedb.org
    answer: 13.249.134.90
  blocked_services: []
  customresolver: null
tls:
  enabled: false
  server_name: ""
  force_https: true
  port_https: 8443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: |
    -----BEGIN CERTIFICATE-----
    MIIFdDCCBFygAwIBAgIQAzXLV+uS6BjIR81YmqjqcDANBgkqhkiG9w0BAQsFADBu
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMS0wKwYDVQQDEyRFbmNyeXB0aW9uIEV2ZXJ5d2hlcmUg
    RFYgVExTIENBIC0gRzEwHhcNMjEwMzI1MDAwMDAwWhcNMjIwMzI1MjM1OTU5WjAY
    MRYwFAYDVQQDEw1idC5tYWpvcmsud2luMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEApMBz0l53rok+KHfkUM5FvSEUfzT5yOKKGlmgkLwkL4ShLQ61DHwQ
    UFJVuMRXdEb/ldg6ncVcKHI7iCNeg8EbFemhUv1aBJfTOwMMEkDuBLezK6Gpy9sq
    Uul6V7IkHcTpriidj81w30Sr3HzZbj+cf2AZyYj5Cl4OnM9EKsgCH4FyrOglwrLq
    NRyWiq740navrGDglLzzrdjUIUVQ/xAmOX2+uMORsMDY5N/MtrMkSwKXyKqQcrmA
    CoDgW+YYBukXT7u5jIyh3OnmJ1hdK+m2xcpHKJ+JAgSYONsC8IURrOxqGFP8QoCY
    rnoMVFzhVK1Elp1Pj27ZDWfSqwVFpqpgWQIDAQABo4ICYjCCAl4wHwYDVR0jBBgw
    FoAUVXRPsnJP9WC6UNHX5lFcmgGHGtcwHQYDVR0OBBYEFHsVMeUTmoK6pI+K3n73
    wDNZC9j5MBgGA1UdEQQRMA+CDWJ0Lm1ham9yay53aW4wDgYDVR0PAQH/BAQDAgWg
    MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjA+BgNVHSAENzA1MDMGBmeB
    DAECATApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMw
    gYAGCCsGAQUFBwEBBHQwcjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNl
    cnQuY29tMEoGCCsGAQUFBzAChj5odHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20v
    RW5jcnlwdGlvbkV2ZXJ5d2hlcmVEVlRMU0NBLUcxLmNydDAJBgNVHRMEAjAAMIIB
    AwYKKwYBBAHWeQIEAgSB9ASB8QDvAHYARqVV63X6kSAwtaKJafTzfREsQXS+/Um4
    havy/HD+bUcAAAF4ahJLFAAABAMARzBFAiAm+3wQ4r8WzSSOeZRyXBqwMnYCdyx5
    h0t3pYmVlwwSNQIhAI9Z05EuyWP5DHzTgnqElL2XrdsMZNRQhhp48lWfy6ZHAHUA
    IkVFB1lVJFaWP6Ev8fdthuAjJmOtwEt/XcaDXG7iDwIAAAF4ahJLHwAABAMARjBE
    AiA+EYOiNAsYIwrK45mGJmUryAL2KSx4jCeu8/AtV6RBIgIgazbwxUozcQG7enFX
    airmUNuvNJ0qli1Lnf4co4lJlBYwDQYJKoZIhvcNAQELBQADggEBAKZ8u5ZNh0yB
    3Eey55OxLNoq+Bw5zsjb6CxScs4rwuMkukecVkkzTRtiVrrZ8ZzWNSPbRcm7x/ux
    M0V+KHVWVk394C3dlWYkjlApnfkm/kAsDtHHl9qySXVaQXiOQ72PNDob/m6U0ooG
    JJaKQChZqCidbCpsbtROR2SGTYPSW3FCcTsVjVnF/N7KT4UugQF8bBJ17UPFN8+X
    UNCGo+gVk7jlZl6DbQxp+PdzA5qkLYdZQ+I6jXr4kTsIgVvGl2EatQ5z0FOCtv7u
    PXC8UP00t8z8SdHelMyewk4XgIcK9S2iJAIH0FFKcgsJE586omEGmJngfwHQOHSb
    RvENBFEJeZ4=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEqjCCA5KgAwIBAgIQAnmsRYvBskWr+YBTzSybsTANBgkqhkiG9w0BAQsFADBh
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
    QTAeFw0xNzExMjcxMjQ2MTBaFw0yNzExMjcxMjQ2MTBaMG4xCzAJBgNVBAYTAlVT
    MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
    b20xLTArBgNVBAMTJEVuY3J5cHRpb24gRXZlcnl3aGVyZSBEViBUTFMgQ0EgLSBH
    MTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALPeP6wkab41dyQh6mKc
    oHqt3jRIxW5MDvf9QyiOR7VfFwK656es0UFiIb74N9pRntzF1UgYzDGu3ppZVMdo
    lbxhm6dWS9OK/lFehKNT0OYI9aqk6F+U7cA6jxSC+iDBPXwdF4rs3KRyp3aQn6pj
    pp1yr7IB6Y4zv72Ee/PlZ/6rK6InC6WpK0nPVOYR7n9iDuPe1E4IxUMBH/T33+3h
    yuH3dvfgiWUOUkjdpMbyxX+XNle5uEIiyBsi4IvbcTCh8ruifCIi5mDXkZrnMT8n
    wfYCV6v6kDdXkbgGRLKsR4pucbJtbKqIkUGxuZI2t7pfewKRc5nWecvDBZf3+p1M
    pA8CAwEAAaOCAU8wggFLMB0GA1UdDgQWBBRVdE+yck/1YLpQ0dfmUVyaAYca1zAf
    BgNVHSMEGDAWgBQD3lA1VtFMu2bwo+IbG8OXsj3RVTAOBgNVHQ8BAf8EBAMCAYYw
    HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBIGA1UdEwEB/wQIMAYBAf8C
    AQAwNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdp
    Y2VydC5jb20wQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQu
    Y29tL0RpZ2lDZXJ0R2xvYmFsUm9vdENBLmNybDBMBgNVHSAERTBDMDcGCWCGSAGG
    /WwBAjAqMCgGCCsGAQUFBwIBFhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BT
    MAgGBmeBDAECATANBgkqhkiG9w0BAQsFAAOCAQEAK3Gp6/aGq7aBZsxf/oQ+TD/B
    SwW3AU4ETK+GQf2kFzYZkby5SFrHdPomunx2HBzViUchGoofGgg7gHW0W3MlQAXW
    M0r5LUvStcr82QDWYNPaUy4taCQmyaJ+VB+6wxHstSigOlSNF2a6vg4rgexixeiV
    4YSB03Yqp2t3TeZHM9ESfkus74nQyW7pRGezj+TC44xCagCQQOzzNmzEAP2SnCrJ
    sNE2DpRVMnL8J6xBRdjmOsC3N6cQuKuRXbzByVBjCqAA8t1L0I+9wXJerLPyErjy
    rMKWaBFLmfK/AHNF4ZihwPGOc7w6UHczBZXH5RFzJNnww+WnKuTPI0HfnVH8lg==
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEApMBz0l53rok+KHfkUM5FvSEUfzT5yOKKGlmgkLwkL4ShLQ61
    DHwQUFJVuMRXdEb/ldg6ncVcKHI7iCNeg8EbFemhUv1aBJfTOwMMEkDuBLezK6Gp
    y9sqUul6V7IkHcTpriidj81w30Sr3HzZbj+cf2AZyYj5Cl4OnM9EKsgCH4FyrOgl
    wrLqNRyWiq740navrGDglLzzrdjUIUVQ/xAmOX2+uMORsMDY5N/MtrMkSwKXyKqQ
    crmACoDgW+YYBukXT7u5jIyh3OnmJ1hdK+m2xcpHKJ+JAgSYONsC8IURrOxqGFP8
    QoCYrnoMVFzhVK1Elp1Pj27ZDWfSqwVFpqpgWQIDAQABAoIBAAbUh7i3++Q7gl0x
    I0EKXC/MGEpxys0+PxV6k8KMWj+yEvCIRI9A8XgzAaTIVwvWCbCPp1Z1IS34Fmm9
    daSms9XDutFy+XFpTfOLW8vB71w4tW/gouZ1rpqDXXQXSZIGYN28h1O3468N7MYW
    UvlUH8vUEx2c1R5N6fMsUJopcpUVur69xLEnD+30rlG/VEL5TgnonQUVObpSocZI
    n355pLb82QFkt8FvyN5vFTC8x2pxd7r/w8+k4eOS5Dj/LBHNNNTQ+zs7YMwSi2qW
    vFipw7yYy+NmYUy8xQ3tcLHy2d5pc8z68oxYeRux7B6/rUYe5NSsCF89xX4O1iY5
    LQUOGdUCgYEA1DKs+I+sLTumtv+DOYwvFnPE9f5HF2YguJE4mzuzo03XDrXKPmRw
    t4YS29GrFfyqk2Kbj50iO04naMIVohtZszPlKxCKFCeaRDY8TQ1vMAAb+xxWLizy
    K/DsLEeAQkRX9FLCHpgUtVGl8mCoSHMlx0BPDQOXkVAijK5cpKgfojMCgYEAxsKL
    gbk4ktsQRsUmeEwRa4Do5vEUE4lbkqqtSNVwX8+FJTNV7l9LfBXIjEhwKAHw7CPG
    MBhUIezM0EYbvMb55WDrkEEohagum+YqZAhrmg21ygD0ZS+Eo54ZXjVbguA2B64h
    4YBNaWyPhoa10edzDE/pWDD/cZb8U4yZP3QGX0MCgYAKuUTkit44qvsR5HfNQLhg
    ehlKFT+ifxbIPQ6PScUaS6TCqY0++fR4Ud5CHaZ3xf0Y1bLm3xoLxTdYo/ZT6u3t
    kIHUW1GfEyFIsTT67+LemiLP3e69Bqh2cAZ/dl2U+782KbiFs0nYn/ey+A+JGcie
    +TEFh1jxjwsv8N/dsmFm4QKBgQCQzn4bJdm8zJMgLFSpwinS29lTIALTdPhdc7HJ
    5Y74jtVfU/ZgM9dn8OrqoX/s9fUT5cBnm+H30XEqsFlXANRhtGoK8B3Yur4yYM8z
    kBrs4t417Nohuiv1lKLAyzj/seBLWidfBj3f9/LdPNnMssZUCwhjc1c355uwNzgT
    TbGyxwKBgQCjAVC9PFroLA5lSuJJdu269jjjyvcPaZpAJgZ0Nrrt7Vs4ot5DgV/E
    YdWrYfoHC0K5UcwDMtQd297xwpCcFurwVyZbYFlybPCiU6Zpyzqt540uJUlGTw3G
    dsoNayssTz4SVfGC+8boh9790eROicqiFywsa2ApbtoqYTiZ+/PXhA==
    -----END RSA PRIVATE KEY-----
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://gitee.com/xinggsf/Adblock-Rule/raw/master/rule.txt
  name: 乘风 广告过滤规则
  id: 1
- enabled: true
  url: https://gitee.com/xinggsf/Adblock-Rule/raw/master/mv.txt
  name: 乘风 视频过滤规则
  id: 2
- enabled: true
  url: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_11_Mobile/filter.txt
  name: 移动端广告规则
  id: 3
- enabled: true
  url: https://raw.sevencdn.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
  name: NoCoin Filter List
  id: 4
- enabled: true
  url: https://raw.sevencdn.com/cjx82630/cjxlist/master/cjx-ublock.txt
  name: CJX's uBlock list
  id: 5
- enabled: true
  url: http://sub.adtchrome.com/adt-chinalist-easylist.txt
  name: ChinaList and EasyList
  id: 6
- enabled: true
  url: https://raw.sevencdn.com/cjx82630/cjxlist/master/cjx-annoyance.txt
  name: CJX's Annoyance List
  id: 7
whitelist_filters: []
user_rules:
- ""
dhcp:
  enabled: false
  interface_name: ""
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
schema_version: 7
