bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0
users:
- name: root
  password: $2y$10$8GfLmnbQpS883RMTpGN66.TbyavsPmElcy2aR6vec7xL0YOG.gx52
http_proxy: ""
language: ""
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_host: 127.0.0.1
  port: 5335
  statistics_interval: 1
  querylog_enabled: false
  querylog_file_enabled: true
  querylog_interval: 1
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - 127.0.0.1:6052
  - '[::1]:6052'
  - '[/awsglobalaccelerator.com/]127.0.0.1:6050'
  - '[/awsglobalaccelerator.com/][::1]:6050'
  upstream_dns_file: ""
  bootstrap_dns:
  - 127.0.0.1:6052
  - '[::1]:6052'
  all_servers: false
  fastest_addr: true
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  cache_size: 51200
  cache_ttl_min: 300
  cache_ttl_max: 3600
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: false
  max_goroutines: 0
  ipset: []
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites:
  - domain: wifi.weixin.qq.com
    answer: 127.0.0.1
  - domain: clock.redhat.com
    answer: cn.ntp.org.cn
  - domain: clock.cuhk.edu.hk
    answer: cn.ntp.org.cn
  - domain: https://www.meituan.com
    answer: www.meituan.com
  blocked_services: []
  customresolver: null
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 8443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_11_Mobile/filter.txt
  name: '移动客户端过滤规则'
  id: 1613564314
- enabled: true
  url: https://halflife.coding.net/p/list/d/list/git/raw/master/ad.txt
  name: '综合广告过滤'
  id: 1613564315
- enabled: true
  url: https://raw.sevencdn.com/timlu85/AdGuard-Home_Youtube-Adfilter/master/Youtube-Adfilter-Web.txt
  name: YouTube
  id: 1613564316
- enabled: true
  url: https://raw.sevencdn.com/91ajames/ublock-filters-ulist-youtube/main/blocklist.txt
  name: Google
  id: 1613564317
whitelist_filters: []
user_rules: []
dhcp:
  enabled: false
  interface_name: ""
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
schema_version: 7
